version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nestjs_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:doc/var/lib/postgresql/data

volumes:
  postgres_data: